// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.AppAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DataType")
                        .HasMaxLength(64)
                        .HasColumnType("int");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DisplayGroup")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppEntityId");

                    b.ToTable("AppAttributes");
                });

            modelBuilder.Entity("Core.Entities.AppAttributeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppAttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppAttributeId");

                    b.ToTable("AppAttributeOptions");
                });

            modelBuilder.Entity("Core.Entities.AppAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppAttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ValueText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppAttributeId");

                    b.ToTable("AppAttributeValues");
                });

            modelBuilder.Entity("Core.Entities.AppAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppAudits");
                });

            modelBuilder.Entity("Core.Entities.AppEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("AppEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f715f0e5-cdd3-4dac-80eb-0d07098b916d"),
                            Code = "User",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đây là nơi lưu trữ thông tin cá nhân, chức vụ, phòng ban và tài khoản đăng nhập của từng người trong công ty.",
                            IsDeleted = false,
                            IsSystem = true,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nhân viên"
                        });
                });

            modelBuilder.Entity("Core.Entities.AppPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RequiredCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e74129f3-ea4a-49c2-8371-fc6942888194"),
                            Code = "USER_VIEW",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép xem danh sách tài khoản người dùng có phân trang và tìm kiếm theo tên đăng nhập, họ tên, email hoặc số điện thoại.",
                            Group = "USER",
                            GroupLabel = "Người dùng",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xem danh sách người dùng",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("3b48f126-a6e7-41d6-8119-4bbe0f2548dd"),
                            Code = "USER_VIEW_ALL",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép lấy toàn bộ người dùng đang hoạt động dưới dạng danh sách đầy đủ, thường dùng cho dropdown, gán vai trò hoặc tích hợp nội bộ.",
                            Group = "USER",
                            GroupLabel = "Người dùng",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xem toàn bộ danh sách người dùng (không phân trang)",
                            Order = 2,
                            RequiredCode = "USER_VIEW"
                        },
                        new
                        {
                            Id = new Guid("16624401-8eb2-4d3a-9c80-a9f4b8c9ed02"),
                            Code = "USER_CREATE",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép tạo tài khoản mới: đặt tên đăng nhập, mật khẩu ban đầu, thông tin cá nhân và cờ như quản trị gốc hoặc nhân viên nếu được cấu hình.",
                            Group = "USER",
                            GroupLabel = "Người dùng",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Thêm mới người dùng",
                            Order = 3,
                            RequiredCode = "USER_VIEW"
                        },
                        new
                        {
                            Id = new Guid("ed09e739-05c0-4f91-9c4e-f13968125d63"),
                            Code = "USER_UPDATE",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép chỉnh sửa hồ sơ người dùng (họ tên, liên hệ, mô tả, cờ quyền hệ thống…) ngoại trừ đổi mật khẩu trực tiếp qua luồng reset.",
                            Group = "USER",
                            GroupLabel = "Người dùng",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Cập nhật thông tin người dùng",
                            Order = 4,
                            RequiredCode = "USER_VIEW"
                        },
                        new
                        {
                            Id = new Guid("0baa2484-9cc7-4770-bace-91e8777da256"),
                            Code = "USER_DELETE",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép xóa mềm một hoặc nhiều người dùng; hệ thống thường chặn tự xóa chính tài khoản đang đăng nhập.",
                            Group = "USER",
                            GroupLabel = "Người dùng",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xóa người dùng",
                            Order = 5,
                            RequiredCode = "USER_VIEW"
                        },
                        new
                        {
                            Id = new Guid("e08debda-5c16-403a-869a-eb5349c37ac1"),
                            Code = "USER_RESET_PASSWORD",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép quản trị viên đặt mật khẩu mới cho người dùng mà không cần biết mật khẩu cũ, dùng khi hỗ trợ hoặc khôi phục truy cập.",
                            Group = "USER",
                            GroupLabel = "Người dùng",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Đặt lại mật khẩu người dùng",
                            Order = 6,
                            RequiredCode = "USER_VIEW"
                        },
                        new
                        {
                            Id = new Guid("2c2d6d42-349a-4bde-a2ac-10553b54ac4c"),
                            Code = "USER_AVATAR",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép cập nhật tệp ảnh đại diện (tên tệp đã lưu trữ) gắn với hồ sơ người dùng.",
                            Group = "USER",
                            GroupLabel = "Người dùng",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Cập nhật ảnh đại diện người dùng",
                            Order = 7,
                            RequiredCode = "USER_VIEW"
                        },
                        new
                        {
                            Id = new Guid("e5b173a9-3022-406c-8ab5-4745da8e7e85"),
                            Code = "ROLE_VIEW",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép xem danh sách vai trò có phân trang (kèm thành viên tóm tắt nếu giao diện hiển thị) và xem chi tiết một vai trò theo mã định danh.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xem danh sách và chi tiết vai trò",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("fc1a9fdb-e31a-40a9-9cf9-1be3c714e725"),
                            Code = "ROLE_VIEW_ALL",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép lấy toàn bộ vai trò để chọn nhanh trong form (không phân trang), ví dụ khi gán vai trò cho người dùng.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xem toàn bộ vai trò (lookup)",
                            Order = 2,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("42307ab7-027c-496a-a098-b7cd27fb31e5"),
                            Code = "ROLE_CREATE",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép tạo vai trò mới với tên và mô tả; tên vai trò phải duy nhất trong hệ thống.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Thêm mới vai trò",
                            Order = 3,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("ace7debe-3885-4c6b-b264-357be5892672"),
                            Code = "ROLE_UPDATE",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép chỉnh sửa tên và mô tả của vai trò đã tồn tại, tuân thủ kiểm tra trùng tên.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Cập nhật vai trò",
                            Order = 4,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("7c024160-a173-4e29-8c8f-0ad2d81f2089"),
                            Code = "ROLE_DELETE",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép xóa mềm vai trò và gỡ các liên kết thành viên–vai trò liên quan trước khi xóa.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xóa vai trò",
                            Order = 5,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("5aa8dfe7-2824-4330-a0b9-283eef4b1ee7"),
                            Code = "ROLE_ASSIGN_TO_USER",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép thiết lập danh sách vai trò cho một người dùng cụ thể (thay thế toàn bộ vai trò hiện có của họ theo luồng API).",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Gán vai trò cho người dùng",
                            Order = 6,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("1f3d0401-fa31-47f3-bd30-47b643afd82d"),
                            Code = "ROLE_MEMBER_ADD",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép thêm một hoặc nhiều người dùng vào một vai trò đã có, bỏ qua những người đã thuộc vai trò.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Thêm thành viên vào vai trò",
                            Order = 7,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("4013a204-48d5-4632-937d-abeee0d4e73a"),
                            Code = "ROLE_MEMBER_REMOVE",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép gỡ một hoặc nhiều người dùng khỏi vai trò đã chọn.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xóa thành viên khỏi vai trò",
                            Order = 8,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("352f2e8d-91cd-4f42-a368-1add325ce153"),
                            Code = "ROLE_USER_ROLES_VIEW",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép xem danh sách vai trò đang được gán cho một người dùng cụ thể, kèm thời điểm gán nếu có.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xem vai trò của người dùng",
                            Order = 9,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("8d64accf-d1c7-447d-84bb-1422d2c775fa"),
                            Code = "ROLE_PERMISSION_VIEW",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép xem toàn bộ danh mục quyền trong hệ thống và danh sách mã quyền (định danh) hiện gán cho từng vai trò.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Xem danh mục quyền và quyền được gán cho vai trò",
                            Order = 10,
                            RequiredCode = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = new Guid("135536bc-a10d-4c3b-9d25-a76b67c0302a"),
                            Code = "ROLE_PERMISSION_SET",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép gán lại tập quyền cho một vai trò; hệ thống kiểm tra quyền phụ thuộc (RequiredCode) trước khi lưu.",
                            Group = "ROLE",
                            GroupLabel = "Vai trò",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Cập nhật quyền cho vai trò",
                            Order = 11,
                            RequiredCode = "ROLE_PERMISSION_VIEW"
                        },
                        new
                        {
                            Id = new Guid("c3e8f1a2-6b4d-4e7f-9c0d-2a3b4c5d6e7f"),
                            Code = "SYSTEM_SETTING_COMPANY_INFO",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Description = "Cho phép xem và cập nhật thông tin đơn vị/doanh nghiệp trên hệ thống (tên, mã số thuế, đại diện pháp luật, liên hệ, ngân hàng…).",
                            Group = "SYSTEM_SETTING",
                            GroupLabel = "Cài đặt hệ thống",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Name = "Cài đặt thông tin đơn vị",
                            Order = 1
                        });
                });

            modelBuilder.Entity("Core.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("Core.Entities.AppRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppRolePermissions");
                });

            modelBuilder.Entity("Core.Entities.AppRoleUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppRoleId");

                    b.HasIndex("AppUserId");

                    b.ToTable("AppRoleUsers");
                });

            modelBuilder.Entity("Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRootAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SsoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afd55aae-d6b2-4741-8ada-5131ea70f00d"),
                            Address = "Headquarters",
                            Avatar = "",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seeded root administrator account",
                            Email = "admin@cloud.local",
                            Gender = 0,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsRootAdmin = true,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "System Administrator",
                            Password = "cs80krLdOzJuOkLfDeo4h6uG6CS7dErnbCkhpuBFNkk=",
                            Phone = "0000000000",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Core.Entities.CloudFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("OwnerId");

                    b.ToTable("CloudFiles");
                });

            modelBuilder.Entity("Core.Entities.CloudFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.ToTable("CloudFolders");
                });

            modelBuilder.Entity("Core.Entities.CloudResourcePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanAdd")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CloudResourcePermissions");
                });

            modelBuilder.Entity("Core.Entities.CloudUserStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MaxBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UsedBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CloudUserStorages");
                });

            modelBuilder.Entity("Core.Entities.CompanyInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BankBranch")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BankName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("BusinessRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Country")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("District")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Hotline")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LegalName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Province")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RepresentativeTitle")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Slogan")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Ward")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("CompanyInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4f7fa3c-987b-4569-826e-2b2e92fdb236"),
                            Address = "Số 32A/856 Tôn Đức Thắng, Phường Hồng Bàng, Thành phố Hải Phòng, Việt Nam",
                            BusinessRegistrationDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Việt Nam",
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hungnd@happyecotech.com",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CÔNG TY CỔ PHẦN HỢP TÁC VÀ PHÁT TRIỂN HAPPY ECOTECH",
                            Province = "Hải Phòng",
                            RepresentativeName = "Nguyễn Duy Hùng",
                            TaxCode = ""
                        });
                });

            modelBuilder.Entity("Core.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PreferenceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Core.Entities.AppAttribute", b =>
                {
                    b.HasOne("Core.Entities.AppEntity", "AppEntity")
                        .WithMany("AppAttributes")
                        .HasForeignKey("AppEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppEntity");
                });

            modelBuilder.Entity("Core.Entities.AppAttributeOption", b =>
                {
                    b.HasOne("Core.Entities.AppAttribute", "AppAttribute")
                        .WithMany("Options")
                        .HasForeignKey("AppAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppAttribute");
                });

            modelBuilder.Entity("Core.Entities.AppAttributeValue", b =>
                {
                    b.HasOne("Core.Entities.AppAttribute", "AppAttribute")
                        .WithMany("Values")
                        .HasForeignKey("AppAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppAttribute");
                });

            modelBuilder.Entity("Core.Entities.AppAudit", b =>
                {
                    b.HasOne("Core.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.AppRolePermission", b =>
                {
                    b.HasOne("Core.Entities.AppPermission", "AppPermission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AppRole", "AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppPermission");

                    b.Navigation("AppRole");
                });

            modelBuilder.Entity("Core.Entities.AppRoleUser", b =>
                {
                    b.HasOne("Core.Entities.AppRole", "AppRole")
                        .WithMany("AppRoleUsers")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AppUser", "AppUser")
                        .WithMany("AppRoleUsers")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Core.Entities.CloudFile", b =>
                {
                    b.HasOne("Core.Entities.CloudFolder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId");

                    b.HasOne("Core.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Core.Entities.CloudFolder", b =>
                {
                    b.HasOne("Core.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.CloudFolder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Owner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Core.Entities.CloudResourcePermission", b =>
                {
                    b.HasOne("Core.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.CloudUserStorage", b =>
                {
                    b.HasOne("Core.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.AppAttribute", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Core.Entities.AppEntity", b =>
                {
                    b.Navigation("AppAttributes");
                });

            modelBuilder.Entity("Core.Entities.AppRole", b =>
                {
                    b.Navigation("AppRoleUsers");
                });

            modelBuilder.Entity("Core.Entities.AppUser", b =>
                {
                    b.Navigation("AppRoleUsers");
                });

            modelBuilder.Entity("Core.Entities.CloudFolder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
